update readme + add images
batch1413-earthquake/earthquake-project pull request #9
Opened 2023-11-12 09:36 UTC by messaoudia

2023-11-12 09:37 UTC, messaoudia commented
@all-contributors please add @messaoudia  for code
@all-contributors please add @jalandet for code
@all-contributors please add @maxdelob for code
@all-contributors please add @jlsrvr for code

2023-11-12 09:39 UTC, messaoudia commented
https://github.com/all-contributors
please add @messaoudia for code
please add @jalandet for code
please add @maxdelob for code
please add @jlsrvr for code

2023-11-12 09:40 UTC, messaoudia commented
@all-contributors
please add @messaoudia for code
please add @jalandet for code
please add @maxdelob for code
please add @jlsrvr for code

2023-11-16 13:22 UTC, messaoudia commented
@jlsrvr tu peux faire une relecture ? :)

2023-11-16 13:23 UTC, maxdelob commented
Okay for me @jlsrvr tu peux verifier la syntaxe stp

2023-11-17 09:38 UTC, jlsrvr requested changes

2023-11-17 09:38 UTC, jlsrvr commented on README.md
> +       <td align="center" valign="top" width="14.28%"><a href="https://github.com/jlsrvr"><img src="https://avatars.githubusercontent.com/u/24507606?v=4" width="100px;" alt="jlsrvr"/><br /><sub><b>Ju
```suggestion
       <td align="center" valign="top" width="14.28%"><a href="https://github.com/jlsrvr"><img src="https://avatars.githubusercontent.com/u/24507606?v=4" width="100px;" alt="jlsrvr"/><br /><sub><b>Jules Rivoire</b></sub></a><br /><a href="https://github.com/batch1413-earthquake/earthquake-project/commits?author=jlsrvr" title="Code">💻</a></td>
```

2023-11-17 09:38 UTC, jlsrvr commented on README.md
> +A seismic events is not necessary an earthquake. It can happens for several reason like ice quake, avalanche etc.
```suggestion
A seismic event is not necessarily an earthquake. It can happen for several reasons like an ice quake, an explosion etc.
```

2023-11-17 09:38 UTC, jlsrvr commented on README.md
> +With the recent earthquakes in earth we wanted to provide an application that can help local authorities (rescue services, ...) to determine how much people will be impacted by an earthquake to be ab
```suggestion
With the recent earthquakes on earth we wanted to provide an application that would help local authorities (rescue services, ...) to determine how many people will be impacted by a seismic event to be able to act fast.
```

2023-11-17 09:38 UTC, jlsrvr commented on README.md
> +Among that we want to have a dashboard (Metabase) that help users to understand and track seismic events.
```suggestion
For that we wanted to have a dashboard (Metabase) that would help users to understand and track seismic events.
```

2023-11-17 09:38 UTC, jlsrvr commented on README.md
> +We used USGS api to gather all the data needed.
```suggestion
We extracted the data from the USGS api on seismic events.
```

2023-11-17 09:38 UTC, jlsrvr commented on README.md
> +- **E**:Extract data from USGS and upload it as bronze
```suggestion
- **E**:Extract data from USGS and upload to our bronze layer
```

2023-11-17 09:38 UTC, jlsrvr commented on README.md
> +- **L**:Load data and clean it as silver
```suggestion
- **L**:Load data and clean it to store it in our silver layer
```

2023-11-17 09:38 UTC, jlsrvr commented on README.md
> +- **T**:Transform data to Google BigQuery as gold
```suggestion
- **T**:Transform data to upload it to our gold layer on Google BigQuery
```

2023-11-17 09:38 UTC, jlsrvr commented on README.md
> +> The Gmail alerting has not been yet been developed
```suggestion
> The Gmail alerting has not yet been developed
```

2023-11-18 17:23 UTC, merged